
export const KANAMEMO_SHOW_SETTINGS = 'KANAMEMO_SHOW_SETTINGS';

export const KANAMEMO_SCORE_UPDATE = 'KANAMEMO_SCORE_UPDATE';
export const KANAMEMO_SETTINGS_UPDATE = 'KANAMEMO_SETTINGS_UPDATE';
export const KANAMEMO_RESET = 'KANAMEMO_RESET';
export const KANAMEMO_DEFAULT_STATE = 'KANAMEMO_DEFAULT_STATE';

export const KANAMEMO_GET_NEXT_KANA = 'KANAMEMO_GET_NEXT_KANA';
export const KANAMEMO_ENTER_ROMAJI = 'KANAMEMO_ENTER_ROMAJI';

export const KANAMEMO_SET_MESSAGE_TEXT = 'KANAMEMO_SET_MESSAGE_TEXT';
export const KANAMEMO_INPUT_CHANGE = 'KANAMEMO_INPUT_CHANGE';
export const KANAMEMO_FORM_SUBMIT = 'KANAMEMO_FORM_SUBMIT';

export const KANAMEMO_SHOW_HINT = 'KANAMEMO_SHOW_HINT';
export const KANAMEMO_LEVEL_UP = 'KANAMEMO_LEVEL_UP';

export const KANAMEMO_AUTO_INPUT_TOGGLE = 'KANAMEMO_AUTO_INPUT_TOGGLE';
export const KANAMEMO_AUTO_LEVEL_UP_TOGGLE = 'KANAMEMO_AUTO_LEVEL_UP_TOGGLE';

export const KANAMEMO_HIRAGANA_TOGGLE = 'KANAMEMO_HIRAGANA_TOGGLE';
export const KANAMEMO_KATAKANA_TOGGLE = 'KANAMEMO_KATAKANA_TOGGLE';

export const KANAMEMO_HIRAGANA_LEVEL_CHANGE = 'KANAMEMO_HIRAGANA_LEVEL_CHANGE';
export const KANAMEMO_KATAKANA_LEVEL_CHANGE = 'KANAMEMO_KATAKANA_LEVEL_CHANGE';

export const KANAMEMO_SETTINGS_RESET = 'KANAMEMO_SETTINGS_RESET';

