
export const kanaList = [
  { hiragana: "あ", katakana: "ア", romaji: "a" },
  { hiragana: "い", katakana: "イ", romaji: "i" },
  { hiragana: "う", katakana: "ウ", romaji: "u" },
  { hiragana: "え", katakana: "エ", romaji: "e" },
  { hiragana: "お", katakana: "オ", romaji: "o" },
  { hiragana: "か", katakana: "カ", romaji: "ka" },
  { hiragana: "き", katakana: "キ", romaji: "ki" },
  { hiragana: "く", katakana: "ク", romaji: "ku" },
  { hiragana: "け", katakana: "ケ", romaji: "ke" },
  { hiragana: "こ", katakana: "コ", romaji: "ko" },
  { hiragana: "さ", katakana: "サ", romaji: "sa" },
  { hiragana: "し", katakana: "シ", romaji: "shi" },
  { hiragana: "す", katakana: "ス", romaji: "su" },
  { hiragana: "せ", katakana: "セ", romaji: "se" },
  { hiragana: "そ", katakana: "ソ", romaji: "so" },
  { hiragana: "た", katakana: "タ", romaji: "ta" },
  { hiragana: "ち", katakana: "チ", romaji: "chi" },
  { hiragana: "つ", katakana: "ツ", romaji: "tsu" },
  { hiragana: "て", katakana: "テ", romaji: "te" },
  { hiragana: "と", katakana: "ト", romaji: "to" },
  { hiragana: "な", katakana: "ナ", romaji: "na" },
  { hiragana: "に", katakana: "ニ", romaji: "ni" },
  { hiragana: "ぬ", katakana: "ヌ", romaji: "nu" },
  { hiragana: "ね", katakana: "ネ", romaji: "ne" },
  { hiragana: "の", katakana: "ノ", romaji: "no" },
  { hiragana: "は", katakana: "ハ", romaji: "ha" },
  { hiragana: "ひ", katakana: "ヒ", romaji: "hi" },
  { hiragana: "ふ", katakana: "フ", romaji: "fu" },
  { hiragana: "へ", katakana: "ヘ", romaji: "he" },
  { hiragana: "ほ", katakana: "ホ", romaji: "ho" },
  { hiragana: "ま", katakana: "マ", romaji: "ma" },
  { hiragana: "み", katakana: "ミ", romaji: "mi" },
  { hiragana: "む", katakana: "ム", romaji: "mu" },
  { hiragana: "め", katakana: "メ", romaji: "me" },
  { hiragana: "も", katakana: "モ", romaji: "mo" },
  { hiragana: "や", katakana: "ヤ", romaji: "ya" },
  { hiragana: "ゆ", katakana: "ユ", romaji: "yu" },
  { hiragana: "よ", katakana: "ヨ", romaji: "yo" },
  { hiragana: "ら", katakana: "ラ", romaji: "ra" },
  { hiragana: "り", katakana: "リ", romaji: "ri" },
  { hiragana: "る", katakana: "ル", romaji: "ru" },
  { hiragana: "れ", katakana: "レ", romaji: "re" },
  { hiragana: "ろ", katakana: "ロ", romaji: "ro" },
  { hiragana: "わ", katakana: "ワ", romaji: "wa" },
  { hiragana: "ゐ", katakana: "ヰ", romaji: "wi" },
  { hiragana: "ゑ", katakana: "ヱ", romaji: "we" },
  { hiragana: "を", katakana: "ヲ", romaji: "wo" },
  { hiragana: "ん", katakana: "ン", romaji: "n" },
  { hiragana: "が", katakana: "ガ", romaji: "ga" },
  { hiragana: "ぎ", katakana: "ギ", romaji: "gi" },
  { hiragana: "ぐ", katakana: "グ", romaji: "gu" },
  { hiragana: "げ", katakana: "ゲ", romaji: "ge" },
  { hiragana: "ご", katakana: "ゴ", romaji: "go" },
  { hiragana: "ざ", katakana: "ザ", romaji: "za" },
  { hiragana: "じ", katakana: "ジ", romaji: "ji" },
  { hiragana: "ず", katakana: "ズ", romaji: "zu" },
  { hiragana: "ぜ", katakana: "ゼ", romaji: "ze" },
  { hiragana: "ぞ", katakana: "ゾ", romaji: "zo" },
  { hiragana: "だ", katakana: "ダ", romaji: "da" },
  { hiragana: "ぢ", katakana: "ジ", romaji: "ji" },
  { hiragana: "づ", katakana: "ズ", romaji: "zu" },
  { hiragana: "で", katakana: "デ", romaji: "de" },
  { hiragana: "ど", katakana: "ド", romaji: "do" },
  { hiragana: "ば", katakana: "バ", romaji: "ba" },
  { hiragana: "び", katakana: "ビ", romaji: "bi" },
  { hiragana: "ぶ", katakana: "ブ", romaji: "bu" },
  { hiragana: "べ", katakana: "ベ", romaji: "be" },
  { hiragana: "ぼ", katakana: "ボ", romaji: "bo" },
  { hiragana: "ぱ", katakana: "パ", romaji: "pa" },
  { hiragana: "ぴ", katakana: "ピ", romaji: "pi" },
  { hiragana: "ぷ", katakana: "プ", romaji: "pu" },
  { hiragana: "ぺ", katakana: "ペ", romaji: "pe" },
  { hiragana: "ぽ", katakana: "ポ", romaji: "po" },
  { hiragana: "きゃ", katakana: "キャ", romaji: "kya" },
  { hiragana: "きゅ", katakana: "キュ", romaji: "kyu" },
  { hiragana: "きょ", katakana: "キョ", romaji: "kyo" },
  { hiragana: "しゃ", katakana: "シャ", romaji: "sha" },
  { hiragana: "しゅ", katakana: "シュ", romaji: "shu" },
  { hiragana: "しょ", katakana: "ショ", romaji: "sho" },
  { hiragana: "ちゃ", katakana: "チャ", romaji: "cha" },
  { hiragana: "ちゅ", katakana: "チュ", romaji: "chu" },
  { hiragana: "ちょ", katakana: "チョ", romaji: "cho" },
  { hiragana: "にゃ", katakana: "ニャ", romaji: "nya" },
  { hiragana: "にゅ", katakana: "ニュ", romaji: "nyu" },
  { hiragana: "にょ", katakana: "ニョ", romaji: "nyo" },
  { hiragana: "ひゃ", katakana: "ヒャ", romaji: "hya" },
  { hiragana: "ひゅ", katakana: "ヒュ", romaji: "hyu" },
  { hiragana: "ひょ", katakana: "ヒョ", romaji: "hyo" },
  { hiragana: "みゃ", katakana: "ミャ", romaji: "mya" },
  { hiragana: "みゅ", katakana: "ミュ", romaji: "myu" },
  { hiragana: "みょ", katakana: "ミョ", romaji: "myo" },
  { hiragana: "りゃ", katakana: "リャ", romaji: "rya" },
  { hiragana: "りゅ", katakana: "リュ", romaji: "ryu" },
  { hiragana: "りょ", katakana: "リョ", romaji: "ryo" },
  { hiragana: "ぎゃ", katakana: "ギャ", romaji: "gya" },
  { hiragana: "ぎゅ", katakana: "ギュ", romaji: "gyu" },
  { hiragana: "ぎょ", katakana: "ギョ", romaji: "gyo" },
  { hiragana: "じゃ", katakana: "ジャ", romaji: "ja" },
  { hiragana: "じゅ", katakana: "ジュ", romaji: "ju" },
  { hiragana: "じょ", katakana: "ジョ", romaji: "jo" },
  { hiragana: "ぢゃ", katakana: "ジャ", romaji: "ja" },
  { hiragana: "ぢゅ", katakana: "ジュ", romaji: "ju" },
  { hiragana: "ぢょ", katakana: "ジョ", romaji: "jo" },
  { hiragana: "びゃ", katakana: "ビャ", romaji: "bya" },
  { hiragana: "びゅ", katakana: "ビュ", romaji: "byu" },
  { hiragana: "びょ", katakana: "ビョ", romaji: "byo" },
  { hiragana: "ぴゃ", katakana: "ピャ", romaji: "pya" },
  { hiragana: "ぴゅ", katakana: "ピュ", romaji: "pyu" },
  { hiragana: "ぴょ", katakana: "ピョ", romaji: "pyo" }
];

export const romajiLevelList = {
    1:  ["a",  "i",   "u",   "e",  "o"],
    2:  ["ka", "ki",  "ku",  "ke", "ko"],
    3:  ["sa", "shi", "su",  "se", "so"],
    4:  ["ta", "chi", "tsu", "te", "to"],
    5:  ["na", "ni",  "nu",  "ne", "no"],
    6:  ["ha", "hi",  "fu",  "he", "ho"],
    7:  ["ma", "mi",  "mu",  "me", "mo"],
    8:  ["ya",        "yu",        "yo"],
    9:  ["ra", "ri",  "ru",  "re", "ro"],
    10: ["wa", "wi",         "we", "wo", "n"],
    11: ["ga", "gi" , "gu" , "ge", "go"],
    12: ["za", "ji" , "zu" , "ze", "zo"],
    13: ["da", "ji" , "zu" , "de", "do"],
    14: ["ba", "bi" , "bu" , "be", "bo"],
    15: ["pa", "pi" , "pu" , "pe", "po"],
    16: ["kya", "kyu", "kyo"],
    17: ["sha", "shu", "sho"],
    18: ["cha", "chu", "cho"],
    19: ["nya", "nyu", "nyo"],
    20: ["hya", "hyu", "hyo"],
    21: ["mya", "myu", "myo"],
    22: ["rya", "ryu", "ryo"],
    23: ["gya", "gyu", "gyo"],
    24: ["ja",  "ju",  "jo"],
    25: ["bya", "byu", "byo"],
    26: ["pya", "pyu", "pyo"]
};

export const getRomajiListByLevel = (start = 1, end) => {
	let result = [];
	
	for(let i = start; i < end + 1; i++){
		result = result.concat(romajiLevelList[i]);
	}
	
	return result;
};

export const getKanaListByLevel = (end, start = 1) => {
	const romajiList = getRomajiListByLevel(start, end);
	
	return kanaList.filter(kana => romajiList.includes(kana.romaji));
};